### PR TITLE
Change the android app styles

### PR DESCRIPTION
**Pull request by markusguenther**
The style of the android app is not optimal. The most text components are not centered vertically
and the input text changes the height depending on the inlineLabel property.

This commit does not remove the input lines because this is a component property of
text-input in react native and can be changed in the general behavior.

But to change this you also need the pull request 15.

https://github.com/esbenp/react-native-clean-form/pull/15

Fixes: #9

### CODE REVIEW

**Comment by markusguenther** [comment]
For multiline inputs the alignment should not be centered. Will add this soon (this evening/night)

**Comment by esbenp** [comment]
There are some conflicts here. Can you resolve those and then I will review again? :-)

**Comment by markusguenther** [comment]
Ok conflicts has been resolved :)

**Comment by tylerbuchea** [comment]
What is the word on this? I'm having issues with the forms displaying on Android as well. Would love to have this fix merged in.

**Comment by markusguenther** [comment]
I guess Esben is on it. He already wrote me that he is busy at the moment.

Stay tuned, it will not take so much time anymore ;)

**Comment by tylerbuchea** [comment]
Sorry for being pushy I didn't look at how recent this PR was before I commented. Your response time is more than satisfactory. Thanks for all the hard work @esbenp and @markusguenther 😄

**Comment by markusguenther** [comment]
No problem ... your welcome :)

**Pull request merged**
